config/routes.rb
Matthewnotes::Application.routes.draw do

  root :to => "notes#index"
  match "chapter/:chapter" => "notes#chapter", :as => :chapters
  match "chapter" => "notes#chapter"

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :filename, :number, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
  end

  def chapter
    @current_chapter = Chapter.find_by_number params[:chapter]
    render :layout => "notes_with_sidebar"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Matthew Notes - Bob Di Lorenzo
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags


  %body
    = render "navigation"
    %div.container.span6.offset3
      = yield

app/views/layouts/notes_with_sidebar.haml
!!!
%html
  %head
    %title Matthew Notes - Bob Di Lorenzo
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags


  %body
    = render "navigation"
    %div.nav-collapse.collapse
      %div.container-fluid.span3
        %div.row-fluid
          %table.table.sidebar-nav(data-provides="rowlink")
            %tbody
              - for chapter in Chapter.all.sort
                - if @current_chapter == chapter
                  %tr.active
                    %td
                      = link_to chapter.title, chapters_url(:chapter => chapter.number)
                - else
                  %tr
                    %a{:href => "#{chapters_url(:chapter => chapter.number)}"}
                      %td
                        = link_to chapter.title, chapters_url(:chapter => chapter.number)
    %div.container.span8.notes
      = yield
    %div#footer
      &copy; 2013 Bob Di Lorenzo

    / RefTagger from Logos
    %script{:src => "http://bible.logos.com/jsapi/referencetagging.js", :type => "text/javascript"}
    :javascript
      Logos.ReferenceTagging.lbsBibleVersion = "NIV";
      Logos.ReferenceTagging.lbsLinksOpenNewWindow = true;
      Logos.ReferenceTagging.lbsLogosLinkIcon = "dark";
      Logos.ReferenceTagging.lbsNoSearchTagNames = [ "h2", "h1"];
      Logos.ReferenceTagging.lbsTargetSite = "biblia";
      Logos.ReferenceTagging.tag();

app/views/notes/_matthew_11.haml
%h3 Coming Soon...

app/views/notes/_matthew_12.haml
%h3 Coming Soon...

app/views/notes/_matthew_13.haml
%h3 Coming Soon...

app/views/notes/_matthew_16.haml
%h3 Coming Soon...

app/views/notes/_matthew_17.haml
%h3 Coming Soon...

app/views/notes/_matthew_25.haml
%h3 Coming Soon...

app/views/notes/_matthew_26.haml
%h3 Coming Soon...

app/views/notes/_matthew_27.haml
%h3 Coming Soon...

app/views/notes/_matthew_3.haml
%h3 Matt 3:1-17
%h4 Mark 1:1-9, Luke 3:1-22, John 1:6-8, 19-34
%h4 Outline:
%ul
  %li V.1-6
  %ul
    %li Who is John?
    %li The Kingdom of Heaven
    %li John’s Baptism
  %li V. 7-12
  %ul
    %li Rebuke of Unbelieving Jews (National Israel)
    %li Allusion to the church (or remnant)
    %li Fruit of Repentance
  %li V. 13-17
  %ul
    %li Jesus Baptism (why?)
  %br
%h3 V. 1-6
%ul
  %li Setting: Now Tiberius Ceasar (AD 14-37)
  %li son in law adopted by Augustus declared co-regent then assumed reign upon Aug. death, Julian dynasty till mid 60’s, Military style leadership
  %li followed by Caligula and Claudius, then Nero
  %li Pontius Pilate (Governor Judea), Herod (Phillip I) the tetrarch of Galilee, (Herod) Philip (II) tetrarch of Iturea (N), Lysanias tetrarch of Abilene, Anna and Caiaphas High Priests (Luke)
  %li Herod the Great’s 3 sons controlled the region after him:
  = succeed " (Judea," do
    %span.s1 Archelaus
  Samaria, Idumea),
  %span.s1 Phillip II
  (Son of Cleopatra, North of Galilee), Antipas (with Herodias later) (Galilee and Perea), Phillip I (first husband of Herodias had daughter Salome), Aristobulus, Alexander, Antipater, then sons of Aristobulus (Agrippa I, Chalcis) and daughter Herodius. Agrippa I then with son Agrippa II and daughters Bernice and Drusilla (Felix marries)
  %li John the Baptist:
  %ul
    %li 300-400 year silence from God and His prophets till John
    %li Malachi 3:1 speaks most directly, recently of John’ coming
    %li He came preaching: and by the foolishness of preaching, the kingdom will be established (1 Cor 1:21, “it pleased God that by the foolishness of preaching, to save those who believe”)
    %li They thought he was “the Christ, Elijah or the Prophet” John 1:20-21
  %li
    V. 3 John the Baptist fulfills Isaiah’s prophesy:
    %b REPENT!
  %ul
    %li Repent: “think again”, “rethink”, “think aright”
    %li Isaiah~ 700BC, prophet to Judah, contemporary of Micah and Hosea. Died under King Manasseh, sawed in two.
    %ul
      %li He condemned Judah for idolatry and empty ritualism and foresaw their coming captivity under Babylon and Israel’s captivity under Assyria was during his lifetime. (Isaiah 40)
      %li Like John the Baptist, he encouraged the remnant to repent for God would deliver a remnant and one day bless those who would make their paths straight
  %li
    John the Baptist came in the same way to precede the Messiah and
    %b exhort them to repentance;
    It was the custom of ancient near eastern kings to send men ahead to clear obstacles for their coming…. To prepare the way. This is fulfilled in John but in the Spirit of Elijah (Mal 3:1, 4:5)
  %li John has come to “make ready a people”, “bring knowledge of salvation” to “give light to those who sit in darkness” (*Luke 1:16-17, 77)
  %li “He came to bear witness of the Light” John 1
  %li Like John, Jesus preaches similarly: Mark 1:14, “the time is fulfilled, repent and believe” …. What time is fulfilled?
  %li John’s Baptism: Of repentance and with confession and then fruits
  %ul
    %li John baptized for cleansing from sin
    %li Baptism: immersion, dipping, submersion, cleansing or to overwhelm
  %li How is John’s Baptism different from ours?
  %ul
    %li
      Acts 2:38, Peter says, "repent and be baptized in the name of Jesus Christ for the remission of sins and you shall receive the gift of the Holy Spirit"
    %li John’s baptism becomes obsolete after Christ comes (preparation for Christ) He then “decreases that Christ may increase”
    %ul
      %li Apollos was a follower of John and gets baptized into Christ
  %li Principal: Gospel truth here: Repentance is the door that must be entered!
  %ul
    %li Grace to the humble (blessed are the poor in spirit, those who mourn)
    %li Resistance to proud (pride comes before a fall)
    %li If one sneaks out, need to come back in through the door of repentance
  %li V.2 “Repent for the Kingdom of Heaven is near” What does this mean? (Central theme in Matthew and Gospels, multiple parables)
  %ul
    %li kingdom of God? The King, His people, His Reign over all in His kingdom
    %li He is the sovereign King, we are the subjects
    %li Fulfillment of OT prophesy
    %li Of the line of David
    %li Over the house of Jacob (Luke 1:33) (New covenant with Judah and Israel)
    %li Over the nations, for Him and against Him, King of Kings, Lord of Lords (Psalm 2, 110, Isa 60:12, Psalm 119:118-119, Psalm 33:12)
    %li Eternal (multiple, Daniel 2, 4:34, Luke, Matt)
    %li Nature: Spiritual but with outward manifestations (Luke 17:20-21)
    %ul
      %li Like our salvation/sanctification (inside out)
      %li Governance: bottom up (decentralized) in contrast to worldly kingdoms
      %li Not like the worldly kingdoms, not of earthly origin (John 18:36)
    %li Taken from one and given to another (Matt 21:43: Parable of Wicked Vinedressers)
    %li The “Kingdom” came with Jesus, but is future in its fullness
    %ul
      %li Progressive and victorious vs. progressive but not victorious?
      %li Heavenly vs. Earthly?
      %li Future in Israel, rebuilt temple with sacrifices, National Israel exalted over the nations?
    %li Jesus receives the kingdom at his ascension (Daniel 7, Luke 19:15, 1 Cor 15)
    %br
%h4 Who was John’s message to? Who was he rebuking?
%ul
  %li V.9 … sons of Abraham
  %ul
    %li Message of mercy but yet judgment for those who reject Christ
    %li The “ax is already at the root of the tree”
    %li Stones to become children if needed
    %li Ax is at the root of the tree (parable of wicked vinedressers Matt 21)
    %li “only those who are of faith are the (true) sons of Abraham” Gal 3:7
    %ul
      %li The blessings are to Abraham and his seed (Christ and people of faith) Gal 3:14, 4:29
      %li This is the “Israel of God” Gal 4:16 (?) (Circle Diagrams)
      %li John “born not of blood… but of the Spirit”
      %br

%h4 What are fruits worthy of repentance? Works!
%ul
  %li See Luke 3:11-14
  %ul
    %li Giving to those in need
    %li Just weights and measures (tax collector), no stealing!
    %li Contentment and stop intimidation, lying, bribery, lording over those under you
    %li Remember Zaccheus?
%br
%h4 Review
%p For those who missed last week, we have begun the heralding of Christ Jesus in John the Baptist. Here are some highlights covered last week:
%ul
  %li Significance of the great prophet, John the Baptist, coming right on time (Daniel) on the scene after 400 years of “silence” between the testaments,  to “prepare the way of the Lord”, preaching confession and repentance
  %li Introduction to the “kingdom of heaven” (kingdom of God) which will be further unveiled as the King is revealed
  %ul
    %li consists of a King and his subjects, fulfillment of OT prophesy, of the Davidic line, over the “house of Jacob” and over the “nations”, eternal, not of earthly origin, spiritual with outward manifestations (“inside out”)
  %li Call to repentance as the door of salvation
  %ul
    %li when repentance is genuine, it will produce fruit (Luke 3:8-14), (“put off and put on”, Eph 4:17-32)  
  %li Allusion to the church (“God is able to raise up children of Abraham from these stones”)
  %li Coming judgment upon unbelieving Jews (“even now the ax is laid to the root of the trees”, “will thoroughly clean out his threshing floor”)
  %br

%h4 Take Home Application: Bear fruit worthy of Repentance
%ul
  %li Pharisees: religious party began as “holy ones” among Maccabees who were strict law abiding but to oral tradition over scripture (Mishna and Talmud), “separated ones” with respect to the Hellenistic effects upon Maccabees later, small but influential and popular group among the Jews.
  %li Sadducees: heavily Hellenized and aristocratic leaders in Temple policy and practices, rejected prophetic books, accepted only the Torah (Pentateuch), denied the resurrection, angels, etc.
  %li How is John’s Baptism different from ours?
  %ul
    %li Acts 2:38, Peter says, “repent and be baptized in the name of Jesus Christ for the remission of sins and you shall receive the gift of the Holy Spirit”
    %li John’s baptism becomes obsolete after Christ comes (preparation for Christ) He then “decreases that Christ may increase”
    %ul
      %li Apollos was a follower of John and gets baptized into Christ
  %li Principal: Gospel truth here: Repentance is the door that must be entered!
  %ul
    %li Grace to the humble (blessed are the poor in spirit, those who mourn)
    %li Resistance to proud (pride comes before a fall)
%br
%h3 V. 13-17
%h4 Why did Jesus need to be baptized?... “to fulfill all righteousness”
%ul
  %li Through the door of repentance as the second Adam (*federal head)
  %li Born under the law (to fulfill all righteousness)
  %li
    Demonstrated
    = succeed " that" do
      %span.s1 humility
    then leads to exhaltation
  %ul
    %li Not unlike his temptation experience to follow (directed by the Holy Spirit)
%br
%h4 What is the significance of Jesus baptism?
%ul
  %li Holy Spirit empowerment (relationship of the Trinitarian Godhead)
  %li Exemplifies our redemptive experience
  %ul
    %li “buried with him in baptism” Rom 6:4
  %li *Identifies, publically, that Christ is “my beloved Son” (John says, “I have seen and testify that this is the Son of God” John 1:34
  %li Like the miracles that follow, these all testify to His deity, His messiahship, etc.
  %li Inaugurates his “ministry” at age 30+ (probably mid thirties)
  %li If Herod dies 4BC, then Jesus born 5-6 BC
  %li “the lamb of God that takes away the sin of the world” (John 1:29)
  %ul
    %li Jesus is the only means through which sin can be atoned for in all the world!
    %li If it means all the sins of the world, then how could God condemn any to hell?
    %li Through Christ, sin in the world is purged (but not wholly)
  %li John says, “I did not know him” (perhaps knew him, but did not know he was the messiah?)
  %li John then put in prison by Herod due to his exposing Herod’s relationship with his brother Phillips wife, Herodias.

app/views/notes/_matthew_5.haml
%h3 Coming Soon...

app/views/notes/_matthew_6.haml
%h3 Coming Soon...

app/views/notes/_matthew_9.haml
%h3 Coming Soon...

app/views/notes/chapter.html.haml
%h1
  = @current_chapter.title
= render @current_chapter.filename

app/views/notes/index.html.haml
%h1 Welcome to Matthew Notes!
= form_tag("/chapter", :method => "get") do
  = select_tag(:chapter, options_from_collection_for_select(Chapter.all.sort, :number, :title), :class => "span3")
  %br
  = submit_tag("Go", :class => "btn btn-large btn-primary")